/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    units: Unit;
    media: Media;
    testimonials: Testimonial;
    'price-index': PriceIndex;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    units: UnitsSelect<false> | UnitsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'price-index': PriceIndexSelect<false> | PriceIndexSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every unit requires a legal status, a price-check date and at least one real photograph before it can be published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  /**
   * e.g. HO-ASH-1442 — Latin letters and digits, must be unique.
   */
  code: string;
  status: 'draft' | 'published' | 'review' | 'sold';
  featured?: boolean | null;
  /**
   * Keep it short — 40 characters max so the card layout holds.
   */
  title: string;
  /**
   * Use the name as it is known locally.
   */
  area: string;
  type: 'شقة' | 'دوبلكس' | 'تاون هاوس' | 'توين هاوس' | 'بنتهاوس' | 'فيلا';
  /**
   * Digits only, no separators. The site formats it.
   */
  price: number;
  /**
   * A price with no date is not a price.
   */
  priceCheckedAt: string;
  size: number;
  gardenSize?: number | null;
  floor?: string | null;
  rooms: number;
  baths: number;
  saleType: 'أولى' | 'إعادة بيع';
  finishing: 'تشطيب كامل' | 'سوبر لوكس' | 'نص تشطيب' | 'على المحارة';
  handover: string;
  /**
   * Never select 'registered' unless you have seen the registration number and date yourself.
   */
  legalStatus: 'مسجل بالشهر العقاري' | 'حكم صحة ونفاذ' | 'عقد ابتدائي موثق' | 'عقد ابتدائي عرفي';
  /**
   * The person who read the papers. Not the owner's name.
   */
  legalSeenBy: string;
  /**
   * We do not list a unit we have not seen.
   */
  visitedAt: string;
  /**
   * Explain in plain language what the status means and what registration would cost.
   */
  legalNote?: string | null;
  /**
   * This drives the affordability search.
   */
  maxYears: number;
  minDownPct?: number | null;
  /**
   * The first image is the card image. Drag to reorder.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Representative = generated or of a similar unit. The site labels it for the buyer.
         */
        kind: 'real' | 'representative';
        /**
         * Used as alt text for screen readers and for Google.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown under the gallery.
   */
  photosTakenAt?: string | null;
  /**
   * The contracted value, not the asking price.
   */
  soldPrice?: number | null;
  contractedAt?: string | null;
  daysListed?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload at the highest quality you have; the system crops and resizes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the image. Screen readers and Google image search both use this.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardWide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Name, city, unit type and date are all required — anonymous testimonials read as fabricated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  city: string;
  unitType: string;
  dateAr: string;
  /**
   * Keep the client's own register. Colloquial on the investor pages reads as small-scale.
   */
  register: 'colloquial' | 'msa';
  /**
   * Optional, but a verifiable testimonial is worth ten unverifiable ones.
   */
  proofUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create a new revision each month; never edit an old one. Prior revisions stay published at their date.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-index".
 */
export interface PriceIndex {
  id: number;
  publishedAt: string;
  sampleListings: number;
  sampleSales: number;
  rows: {
    area: string;
    avg: number;
    low: number;
    high: number;
    sample: number;
    qoq?: string | null;
    id?: string | null;
  }[];
  /**
   * State exactly what the figure excludes.
   */
  footnote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Requests from the site. The homepage promises a 14-minute median reply.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  phone: string;
  /**
   * Arrives automatically from the page the visitor was on.
   */
  unitCode?: string | null;
  bestTime?: string | null;
  state?: ('new' | 'replied' | 'viewing' | 'contracted' | 'closed') | null;
  note?: string | null;
  /**
   * Originating page.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'price-index';
        value: number | PriceIndex;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  featured?: T;
  title?: T;
  area?: T;
  type?: T;
  price?: T;
  priceCheckedAt?: T;
  size?: T;
  gardenSize?: T;
  floor?: T;
  rooms?: T;
  baths?: T;
  saleType?: T;
  finishing?: T;
  handover?: T;
  legalStatus?: T;
  legalSeenBy?: T;
  visitedAt?: T;
  legalNote?: T;
  maxYears?: T;
  minDownPct?: T;
  gallery?:
    | T
    | {
        image?: T;
        kind?: T;
        caption?: T;
        id?: T;
      };
  photosTakenAt?: T;
  soldPrice?: T;
  contractedAt?: T;
  daysListed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardWide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  city?: T;
  unitType?: T;
  dateAr?: T;
  register?: T;
  proofUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-index_select".
 */
export interface PriceIndexSelect<T extends boolean = true> {
  publishedAt?: T;
  sampleListings?: T;
  sampleSales?: T;
  rows?:
    | T
    | {
        area?: T;
        avg?: T;
        low?: T;
        high?: T;
        sample?: T;
        qoq?: T;
        id?: T;
      };
  footnote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  unitCode?: T;
  bestTime?: T;
  state?: T;
  note?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The facts shown on every page. Colours, fonts and layout are deliberately not editable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  phoneLocal: string;
  phoneIntl: string;
  address: string;
  officeHours: string;
  replyTime?: string | null;
  commercialRegistry: string;
  registryOffice?: string | null;
  taxCard: string;
  brokerageRegistration: string;
  /**
   * Effective January 2026. Essentially no October competitor publishes their number.
   */
  brokerageDecree?: string | null;
  registeredAt?: string | null;
  unitsVisited?: number | null;
  unitsDeclined?: number | null;
  unitsListed?: number | null;
  contractsThisYear?: number | null;
  totalSold?: number | null;
  numbersCheckedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  phoneLocal?: T;
  phoneIntl?: T;
  address?: T;
  officeHours?: T;
  replyTime?: T;
  commercialRegistry?: T;
  registryOffice?: T;
  taxCard?: T;
  brokerageRegistration?: T;
  brokerageDecree?: T;
  registeredAt?: T;
  unitsVisited?: T;
  unitsDeclined?: T;
  unitsListed?: T;
  contractsThisYear?: T;
  totalSold?: T;
  numbersCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}